from .base_options import BaseOptions

 
class TrainOptions(BaseOptions):
    def initialize(self, parser):
        parser = BaseOptions.initialize(self, parser)
        parser.add_argument('--earlystop_epoch', type=int, default=15)
        parser.add_argument('--data_aug', action='store_true', help='if specified, perform additional data augmentation (photometric, blurring, jpegging)')
        parser.add_argument('--optim', type=str, default='adam', help='optim to use [sgd, adam]')
        parser.add_argument('--new_optim', action='store_true', help='new optimizer instead of loading the optim state')
        parser.add_argument('--loss_freq', type=int, default=400, help='frequency of showing loss on tensorboard')
        parser.add_argument('--save_latest_freq', type=int, default=2000, help='frequency of saving the latest results')
        parser.add_argument('--save_epoch_freq', type=int, default=20, help='frequency of saving checkpoints at the end of epochs')
        parser.add_argument('--continue_train', action='store_true', help='continue training: load the latest model')
        parser.add_argument('--epoch_count', type=int, default=1, help='the starting epoch count, we save the model by <epoch_count>, <epoch_count>+<save_latest_freq>, ...')
        parser.add_argument('--last_epoch', type=int, default=-1, help='starting epoch count for scheduler intialization')
        parser.add_argument('--extra_dataroot', type=str, default=None, help='additional dataset root to mix into training')
        parser.add_argument('--train_split', type=str, default='train', help='train, val, test, etc')
        parser.add_argument('--val_split', type=str, default='val', help='train, val, test, etc')
        parser.add_argument('--niter', type=int, default=100, help='# of iter at starting learning rate')
        parser.add_argument('--beta1', type=float, default=0.9, help='momentum term of adam')
        parser.add_argument('--lr', type=float, default=0.00005, help='initial learning rate for adam')
        parser.add_argument('--weight_decay', type=float, default=1e-4, help='weight decay for Adam optimizer')
        parser.add_argument('--fc1_wd', type=float, default=0.01, help='L2 penalty factor on fc1 weights (prevents explosion)')
        parser.add_argument('--time_limit', type=float, default=0, help='max training time in hours (0 = no limit)')
        parser.add_argument('--use_attn_pool', action='store_true', help='use attention pooling instead of GAP')
        parser.add_argument('--multi_scale', action='store_true', help='use 3-scale NPR (0.25/0.50/0.75)')
        parser.add_argument('--use_sobel', action='store_true', help='enable Sobel edge-guided weighting')
        parser.add_argument('--use_tkp', action='store_true', help='replace GAP with Top-K Pooling')
        parser.add_argument('--use_post_bn', action='store_true', default=True, help='add BatchNorm after GAP (normalises all-positive features)')
        parser.add_argument('--no_post_bn', action='store_false', dest='use_post_bn', help='disable post-GAP BatchNorm')
        parser.add_argument('--tkp_k', type=int, default=5, help='K for Top-K Pooling')
        parser.add_argument('--tkp_alpha', type=float, default=0.3, help='auxiliary loss weight for TKP')
        parser.add_argument('--freq_aug_prob', type=float, default=0.3, help='probability of random frequency attenuation')
        parser.add_argument('--freq_aug_alpha', type=float, default=0.3, help='strength of frequency attenuation')
        parser.add_argument('--jpg2_prob', type=float, default=0.1, help='probability of double JPEG compression')
        parser.add_argument('--noise_prob', type=float, default=0.1, help='probability of Gaussian noise injection')
        parser.add_argument('--noise_sig', default='1.0', help='sigma for Gaussian noise injection')
        # parser.add_argument('--model_path')
        # parser.add_argument('--no_resize', action='store_true')
        # parser.add_argument('--no_crop', action='store_true')
        self.isTrain = True
        return parser
